// Single-decision work-photo route regression guard.
const fs = require('fs');
const assert = require('assert');
const source = fs.readFileSync('TarsReportApp.js', 'utf8');
const a = source.indexOf('async function shouldForwardConfirmedWorkPhoto');
const b = source.indexOf('async function fastForwardPersonalReportPhotos', a);
assert(a >= 0 && b > a, 'dedicated helper must exist');
const h = source.slice(a, b);
assert.strictEqual((h.match(/personalImageKindForPreUpload\(/g) || []).length, 1, 'work-photo helper must make one classification decision');
assert(!h.includes('requestOpenAiReceiptCheck'), 'work-photo helper must not call OpenAI a second time');
assert(h.includes('finalKind === \"photo\"'), 'confirmed photo must forward');
assert(h.includes('finalKind === \"receipt\"'), 'receipt must block');
assert(h.includes('finalKind === \"mailing\"'), 'mailing proof must block');
assert(h.includes('finalKind || \"unknown\"'), 'unknown must remain blocked');
const c = source.indexOf('async function fastForwardPersonalReportPhotos');
const d = source.indexOf('async function publishDirectReportPhotos', c);
const f = source.slice(c, d);
assert(f.includes('shouldForwardConfirmedWorkPhoto('), 'forwarder must use dedicated decision helper');
assert(f.includes('FAST_PHOTO_FORWARD_CONFIRMED'), 'forwarding must log confirmation');
assert(!f.includes('FAST_PHOTO_FORWARD_DEFAULT_TO_PHOTO'), 'unknown must never default to report photo');
console.log('PASS: dedicated work-photo forwarding uses one final classification decision');
