const fs = require('fs');
const assert = require('assert');

const source = fs.readFileSync('TarsReportApp.js', 'utf8');
const linkStart = source.indexOf('async sendPersonalReportLink');
const linkEnd = source.indexOf('async publishDefaultTable', linkStart);
const linkBlock = source.slice(linkStart, linkEnd);
const selectorStart = source.indexOf('async sendPersonalImageSelector');
const selectorEnd = source.indexOf('cashLauncherAssociation', selectorStart);
const selectorBlock = source.slice(selectorStart, selectorEnd);
const promptStart = source.indexOf('async sendUnknownImageTypePrompt');
const promptEnd = source.indexOf('async executeActionButtonHandler', promptStart);
const promptBlock = source.slice(promptStart, promptEnd);
const selectionStart = source.indexOf('async ensureManualImageSelection');
const selectionEnd = source.indexOf('async removeManualImageSelectionPrompt', selectionStart);
const selectionBlock = source.slice(selectionStart, selectionEnd);
const postStart = source.indexOf('async executePostMessageSent');
const postEnd = source.indexOf('async receiptOcrConfig', postStart);
const postBlock = source.slice(postStart, postEnd);
const classifyStart = source.indexOf('async function personalImageKindForPreUploadUncached');
const classifyEnd = source.indexOf('async function personalImageKindForPreUpload(', classifyStart);
const classifyBlock = source.slice(classifyStart, classifyEnd);
const menuStart = source.indexOf('async handleUploadMenuButton');
const menuEnd = source.indexOf('async handlePhotoReportButton', menuStart);
const menuBlock = source.slice(menuStart, menuEnd);

assert.doesNotMatch(linkBlock, /UPLOAD_MENU_ACTION|➕ ЗАГРУЗИТЬ/);
assert.doesNotMatch(linkBlock, /PHOTO_REPORT_ACTION|RECEIPT_UPLOAD_ACTION|MAILING_UPLOAD_ACTION/);
for (const label of ['📸 ФОТО', '🧾 ЧЕК', '✉️ РАССЫЛКА']) assert.match(selectorBlock, new RegExp(label));
assert.doesNotMatch(promptBlock, /newButtonElement|UPLOAD_MENU_ACTION/);
assert.match(selectionBlock, /Что вы отправили\?/);
assert.match(selectionBlock, /MANUAL_IMAGE_RECEIPT_ACTION/);
assert.match(selectionBlock, /MANUAL_IMAGE_PHOTO_ACTION/);
assert.match(selectionBlock, /MANUAL_IMAGE_MAILING_ACTION/);
for (const label of ['📸 ФОТО', '🧾 ЧЕК', '✉️ РАССЫЛКА']) assert.match(menuBlock, new RegExp(label));
assert.match(postBlock, /const intentCount = \[explicitPhotoIntent, explicitTransferIntent, explicitMailingIntent\]\.filter\(Boolean\)\.length/);
assert.match(postBlock, /if \(intentCount !== 1\) \{[\s\S]*handleUploadMenuButton[\s\S]*return;/);
assert.doesNotMatch(postBlock, /ensureManualImageSelection/);
assert(postBlock.indexOf('intentCount !== 1') < postBlock.indexOf('primaryVisionDecisionForPersonalMessage'), 'one preselected type must precede primary Vision');
assert.match(classifyBlock, /primaryVisionDecisionForImage[\s\S]*primaryVisionDominantKind\(primaryDecision\)[\s\S]*if \(dominantKind\) return dominantKind;[\s\S]*if \(ocrReceipt\) return "receipt";/);
assert.match(source, /for \(const messageFile of imageFiles\)/);

console.log('PASS: three pre-upload choices gate one Vision-confirmed image pipeline');
