const fs=require("fs"),assert=require("assert");
const s=fs.readFileSync("TarsReportApp.js","utf8");
const a=s.indexOf("async function fastForwardPersonalReportPhotos");
const b=s.indexOf("async function",a+50);
const x=s.slice(a,b>0?b:s.length);
assert(x.includes('intent === "mailing" || intent === "receipt"'),"receipt/mailing guard preserved");
assert(x.includes("shouldForwardConfirmedWorkPhoto"),"existing classification gate preserved");
assert(x.includes("FAST_PHOTO_FORWARD_FALLBACK_OK"),"delivery fallback exists");
assert(x.includes("modify.getCreator().startMessage"),"fallback uses existing Rocket.Chat creator");
assert(x.indexOf("FAST_PHOTO_FORWARD_FALLBACK_OK") > x.indexOf("shouldForwardConfirmedWorkPhoto"),"fallback runs only after photo guard");
console.log("PASS: guarded photo forwarder has direct Rocket.Chat delivery fallback");
