const fs=require("fs"),assert=require("assert");
const s=fs.readFileSync("TarsReportApp.js","utf8");
const a=s.indexOf("async function fastForwardPersonalReportPhotos");
const b=s.indexOf("async function",a+50);
const x=s.slice(a,b>0?b:s.length);
assert(x.includes('intent === "mailing" || intent === "receipt"'),"receipt/mailing guard preserved");
assert(x.includes("shouldForwardConfirmedWorkPhoto"),"existing classification gate preserved");
assert(!x.includes("FAST_PHOTO_FORWARD_FALLBACK_OK"),"cross-room upload reuse fallback must be removed");
assert(x.includes("native forwarded report photo message"),"native forward failure must remain observable");
console.log("PASS: guarded photo forwarder relies on Rocket.Chat native forwarding");
