// Repeated Rocket.Chat events must not repeat the photo acceptance message.
const fs = require('fs');
const assert = require('assert');
const source = fs.readFileSync('TarsReportApp.js', 'utf8');
assert(source.includes('return "already-published"'), 'already published photo events must return a non-new status');
assert(source.includes('return "duplicate"'), 'duplicate photo events must return a duplicate status');
assert(source.includes('if (photoEntries.length && workPhotoForwarded) await notifyWorkPhotoAccepted'), 'the unified pipeline must confirm only a photo actually forwarded to results');
assert(source.includes('if (photoResult === true) await notifyWorkPhotoAccepted'), 'the direct result route must not confirm duplicate or already-published events');
const publisherStart = source.indexOf('async function publishDirectReportPhotos');
const publisherEnd = source.indexOf('async function publishPendingReportPhotos', publisherStart);
assert(publisherStart >= 0 && publisherEnd > publisherStart, 'direct report photo publisher must exist');
const publisher = source.slice(publisherStart, publisherEnd);
assert(publisher.includes('let changed = false;'), 'publisher must track persistence changes separately');
assert(publisher.includes('let forwarded = false;'), 'publisher must track actual result delivery separately');
assert(publisher.includes('return forwarded;'), 'publisher result must mean actual delivery, not merely a handled block');
const blockedStart = publisher.indexOf('if (!confirmedDecision.forward)');
const blockedEnd = publisher.indexOf('const existingForward', blockedStart);
assert(blockedStart >= 0 && blockedEnd > blockedStart, 'blocked work-photo branch must exist');
assert(!publisher.slice(blockedStart, blockedEnd).includes('forwarded = true'), 'a blocked photo must never be reported as forwarded');
assert.strictEqual((source.match(/setText\("✅ ФОТО РАБОТЫ ПРИНЯТО"\)/g) || []).length, 1, 'there must be one acceptance-message emission path');
console.log('PASS: repeated photo events cannot duplicate acceptance confirmation');
